language: node_js
node_js:
- node
deploy:
  provider: npm
  email: remcohaszing@gmail.com
  api_key:
    secure: E3wYGco7kX6GKO563QxzoDN5+sTOAiwI8RmkO+rbzfaL+dJqDHlrp0LSDRdIcS2tYj/3gq2HtQPW2DWN/sp+l0ke1Um9fIpe9kgqVt8D0bWzmKd61hDjhbjXzq4W2l8K2ThI+odzBiN/uM+scP8QpvMMakIjIankT15APV6/zo7wjGo5eHIVfXv1AZr4ePZeZy8Bxv9527U9JBzjtw5Iow7MZ+SQXJ/vm8IbH2ntV9nRmg+WC8HBLEHBLkGW3R5w6Wl5jZDbJmEOiw+3DQPh4IwOr7eiUp+RavJG5T8gzQsVNiCvgFdOLYNYUkbQUqMA8EFq2Fmr1ZHkUbjzQsw8dr90W7jkg0o7h8nlO9ttaKuTh5kSe7DR4nIiL3Xkm/gooNNCHFUc+DT18ck6lwAgExqrRk05WmgP1/hyiRkRb1T9v4Y1JvJ2kk7GoPDhA6ObJTGZJH7bIJXDwyT3oLenH8nMBE+Xpl2eBk1Ydfg+TUsVbHvWR1yIS/ZHAtdx6PZcGOBb47kVKd5SZS8Cw5sJN+NjiVPhltJxFCmBwmmKFY9RCBGLDSTOmJTeDdSfFakfFVBz1GlQ6z2TpJIwt9kz3hRNdPvM1JoiC8F3uvs5lq6FlrmMlgPZOfHXZ2Wm/VMr3AFy64/VOGhEIYHOEZ2gZzngu6YbBV2Z+v6gwovsICU=
  on:
    tags: true
    repo: remcohaszing/generate-cordova-assets
